apiVersion: v1
kind: Secret
metadata:
  name: api-db-secret
  namespace: api
immutable: false
type: Opaque
data:
  mongouri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZXMubW9uZ28uc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvY29udHJpYnV0b3I=
  redisuri: cmVkaXMtc2VydmljZXMucmVkaXMuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  basicauthpassword: cGFzc3dvcmQ=
  basicauthusername: YWRtaW4=

