name: Create Release
on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Creating Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Creating Tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.PA_TOKEN }}
          output-file: "false"
          create-summary: 'true'
          version-file: './version.yaml'

      - name: Create Release
        if: steps.changelog.outputs.skipped == 'false'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PA_TOKEN }}
          tag	: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
